### ISSUE TITLE
[Feature] Basic/large tuner view

### ISSUE THREAD

**Issue by pssandhu** [thetwom/Tuner#15]
The tuner works great. The only difficulty I have is that it's hard to use quickly or at a distance/with bad eyesight (e.g. arm's length on a music stand) because of the small text and relatively large number of things on the screen.

I would love to see a basic tuner view with just a horizontal cents scale, the current target note in the middle, and a moving indicator. Alternatively, it could be a speedometer style tuner with a rotating needle which might be nicer.

Perhaps a red light on either side for sharp or flat and a green one in the middle for in tune. The separation would help with clarity and colour blindness.

**Comment by thetwom** [comment]
Thanks for the suggestions. I understand that the current view is not ideal for many cases. I was indeed thinking of introducing a more simple mode, without showing any spectra or correlations, which are of no use for most users anyway.

I still think it is a good idea to somehow visualize part of the history of the pitch, but I agree that it can be much better tailored to the task of tuning to one note. Might take a while until I find time  working on this ...

**Comment by Akira25** [comment]
I love this app for the historical visualization of the pitch and the spectral stuff. It should definitely keep this. It's really practical for tuning.
I like the idea of having an expert-mode (current UI) and maybe a simple mode with an easier UI.

**Comment by thetwom** [comment]
I definitely plan to keep the current UI in some way, since it gives more insight of what is happening and it can help if the frequency detection goes wrong. But I guess, that for most people an additional simple mode will be quite helpful. But as said ... it might take a while until I find time ...

**Comment by thetwom** [comment]
Thanks a lot for the thorough testing and feedback:
- I can't reproduce the first bug you are mentioning. Can you give me some of your phones details (screen resolution, android version).
- Second bug I can confirm. Will provide a version with a fix soon. 
- Design: you are right, that I did not highlight some elements as buttons and maybe I should change this. Not sure yet, how to do and still keeping a more or less clean design. Standard ways are using another color or elevate the element a bit. I did not use elevation for this app at all so it might look a bit off. Maybe I have to find a suitable color. Yes, the direction of the arrow is not intuitive ... the idea was to show the direction it will scroll ... but when using it, it  does not look right.

**Comment by thetwom** [comment]
Here is a version with some improvements [v2.0.0-beta1](https://github.com/thetwom/Tuner/releases/tag/v2.0.0-beta1) (sorry, I accidentally screwed up the version naming, but the link points to the new version). I changed a few things, but not sure if it fixed the first bug, you reported above. Second bug is fixed. Design is a changed a bit such that I replaced the pointing arrows now with a "center-to-note"-icon, which is hopefully more intuitive. There is still no highlighting of buttons, since I have no good solution here yet. 

Accidentally, I published the previous version (as said,  I screwed up the version naming a bit and then fdroid picked it up) ... so I will publish this fixed version soon ...

**Comment by pssandhu** [comment]
I've tried the newest version you have provided here and the second bug is fixed for me too but the first is still there. It's a little inconsistent to reproduce, sometimes it takes switching the mode and pressing the back nav button then switching again and going back a second time. I am on android 8.0.0 with a 2280x1080 screen.

I also just now realised you can anchor to a note by tapping on it in the top view... That would explain why it uses a different button to recentre rather than the same indicator as the rest of the graphs.

**Comment by thetwom** [comment]
Thanks for the further testing. I will try if I can reproduce the bug on android 8.0.0. I guess, this problem is also happening when switching back to the "simple" mode? When restarting the app after switching to scientific mode, does the scientific mode work correctly (i.e. no freezes)?

You are right, the "recentre"-behavior of the different plots is not perfectly consistent. I first had it this way, but allowing to anchor the notes does take away the option to have recentre-on-click. So I changed it to the current behavior. If there are ideas how to make things more consistent, I would be glad to here them. Was thinking about double-click, but this is not so intuitive first hand ...

**Comment by thetwom** [comment]
Tried 8.0.0 now but still can't reproduce. With screen-freeze, does it mean, that now sound curves are shown ore does it mean, that the app is totally stuck (can you e.g. scroll or switch back to settings)?

**Comment by pssandhu** [comment]
By "freeze" I mean it looks like the app is not detecting any sound input and the graphs are no longer updating. The line on the graph may or may not be grey. However, you can interact with the app (scroll the graphs, access the settings etc.) as normal. Both scientific and basic mode can become like this. Restarting or minimising and switching back to the app fixes it.

**Comment by thetwom** [comment]
Thanks for the details. I think, I found the reason. Could you please try if [v2.0.1-beta1](https://github.com/thetwom/Tuner/releases/tag/v2.0.1-beta1) fixes it? Please also try if pressing back from different positions works as expected. The situation of having two different modes is a bit tricky to make it work correctly.

**Comment by pssandhu** [comment]
Yeah, I think that's fixed it. I can't find any other problems with switching between modes, going back from the settings page, or pressing either back button. I'm glad we could get to the bottom of this.

Also, I think the change you made to the recentre icon works quite well because it only appears after you scroll the graph and the arrows give it a "click me" feeling. Much more intuitive than before.
