### ISSUE TITLE
Add viola and cello tunings

### ISSUE THREAD

**Issue by dbolton** [thetwom/Tuner#18]
How about including the orchestral string instruments to the default instrument list? 
- Viola: C3, G3, D4, and A4
- Cello: C2, G2, D3 and A3

We already have Violin and Double Bass (4-string bass).

By the way, I love the app and the new custom tunings feature.

**Comment by thetwom** [comment]
Thanks for the feedback.

I guess, your suggestion make sense. Of course, the default list shouldn't get to long, but having the standard orchestral strings seems reasonable.

**Comment by thetwom** [comment]
Here is a prerelease with some more tunings, as well as other mostly under-the-hood changes ... maybe you can double-check that the tunings are correct. [v3.1.0-rc1](https://github.com/thetwom/Tuner/releases/tag/v3.1.0-rc1)

**Comment by dbolton** [comment]
I tested them all in the latest release candidate and they all have the right tuning. Thank you!

Note: the tuner app had a hard time detecting the pitch of the lowest bass note. Not sure if that's a problem with my speakers (I don't have an acoustic bass to test with and can't sing that low) or a problem with the pitch detection settings. All the other pitches detected without issue.

**Comment by thetwom** [comment]
Thanks a lot for testing. Good to hear that everything is correct. Detecting very low notes is indeed a bit "harder", since the lowest possible frequencies is the main factor of the update rate (how often per second we can find a new tuning) and also it makes the detection a bit more expensive (meaning more cpu power). But the presets work for me fine for an 5-string e-bass, where the lowest note is B0. 

That said, the low-frequency behavior can be improved by going to the settings and increasing the window size to 16384 or even 32768. But as said, this comes at the cost of a lower update rate. But as long as you don't have and bass, you don't have to test this, it's just for your information. 

I will try to release an official version within the next days.

**Comment by thetwom** [comment]
This is now released as [v3.1.0](https://github.com/thetwom/Tuner/releases/tag/v3.1.0), should be available on fdroid and google play within the next days
