### ISSUE TITLE
material you

### ISSUE THREAD

**Issue by andsofine** [thetwom/Tuner#20]

**Comment by andsofine** [comment]
> thanks for the suggestion, I guess you are right and it's time to switch to the new design guidelines. Will upload a test version next week. If you don't bother to build yourself, you can try the "materialyou"-branch ...
> 
> All in all there are not too many changes. We still need red and green colors for "in-tune" and "out-of-tune".

can green and red also be slightly adjusted to the shades that are well-established in the material you?

**Comment by andsofine** [comment]
I'm not talking about this way of harmonization. I'm talking about something like this: 
![4af45c55c89ac505dd28a560af-removebg-preview](https://user-images.githubusercontent.com/99369164/170123534-752a004c-da90-4e99-8699-43475b952038.png)

harmonization by circles. it happens that apps choose different colors based on wallpaper, but basically the main colors are the same (or very close similar)
so that's how we can harmonize them. we take green and red from a circle where the material you takes its main color (in night mode, the main color is different and is harmonized in the same way)

**Comment by thetwom** [comment]
You are talking about harmonizing colors, if a main color is known. But the first time, when this color is known, is at app start. One would have to check if it is possible to modify the current way of theming, introducing and generating new colors on the fly (besides the one which are provided by the system). This would feel more like fighting against the preexisting functionality, than embracing it ... I am preferring the latter :-). But I guess it will be still good enough.

**Comment by andsofine** [comment]
looks like I lost. but they don't use some shades. if dark shade in a light theme, only some specific ones, obviously not anything.
okay, in fact, this red and green suits me, I don’t know how they will be against the background of the material, but I think it’s good.
wanted to ask you to use pale colors, the same as in the material file. not like infinity for reddit please

I also wanted to ask if the black stripes on top and bottom will be painted?
![Screenshot_20220525-005312](https://user-images.githubusercontent.com/99369164/170138853-1e9754a0-ce57-4f32-87a9-880e5700a9b7.png)

**Comment by andsofine** [comment]
> 

it's definitely possible. the bottom part of the material files is colored as you can see in the screenshot that I sent. 

I just checked and there is not even a painted bottom line
![Screenshot_20220525-184656](https://user-images.githubusercontent.com/99369164/170304634-9580ee3d-525a-4d48-9138-e1a861b04f54.png)

also you can see this if it helps:
https://gitlab.com/techbeeat1/jtx/-/issues/202

it might not look good if the colors are chosen like in infinity for reddit or a simple gallery pro.
but this applies to the entire app, not just the notification bar

the background color of the notification bar should be the same as that of the top bar. to make them look like one

**Comment by andsofine** [comment]
> interesting link, based on this I think I remember, why I set the status bar always to black ... it seems not easy to control the font color of the status bar. So black was a safe option :-). But if I understand the link correctly, we get more control with the newer APIs. I this indeed is the case without having to fight too much, I will change it for newer APIs.

it may be worth changing just as it is said in the link to change only a piece of code for a new api for newer versions of android.
without reducing the number of supported devices

**Comment by thetwom** [comment]
yes, I did investigate a bit and the status bar can be adapted for all supported devices. The navigation bar only works for android 8+.

**Comment by thetwom** [comment]
Thanks a lot for testing!

> I think light mode could be more prone to color shift. I'm talking about a lot of black elements, but I'm not sure yet

You mean, that the elements could be more colored? So not using black lines and text, but some colors from the theme? It seems to me, that using more color can easily make things worse. Since I am no designer it is very hard to judge what looks right and what looks bad. So, I would rather like to keep it.

> and In dark theme, the notification bar and navigation bar do not adjust to the background of the app

From your screenshot I guess, you mean the icons (like wifi, battery, ...) should appear white, but are black so they can't be seen? Can I ask, which Android version you are using?

**Comment by thetwom** [comment]
Thanks, now I see the small color difference. I indeed got a color wrong at one place, but it should not have affected newer android versions. However, I am also setting the dark theme background now to pure black as requested in issue #23. In my tests the coloring seems to be correct now. Here is the rc: [v4.0.0-rc2](https://github.com/thetwom/Tuner/releases/tag/v4.0.0-rc2)

**Comment by thetwom** [comment]
very strange, I guess I have to find out better, what is happening here. I indeed was trying to make everything pure black. Can you let me know you Android version, so I can test better?

I tried both, having an almost black and a fully black background. It does not make a real difference. From the Material Design guide I am reading, that pure black is avoided especially if there are larger areas which are bright. But for simple things like text, pure black seems to be totally fine. Since we hardly have any bright areas, pure black might fine. But I guess it would be good to have a few more opinions ... . An extra setting could help to make everyone happy, but highly user-customizable theming is not foreseen in the standard android libs, which means much more code, which I would like to avoid. Again on the othe side some things can be adjusted easily, so I don't say, that I won't add extra options ...

**Comment by thetwom** [comment]
Thanks for providing the android version. I indeed got something wrong how colors are resolved. I hope this is fixed now: [v4.0.0-rc3](https://github.com/thetwom/Tuner/releases/tag/v4.0.0-rc3). This is using no pure black for now, since it is not as easy as I hoped to do it. 

Four separate settings for just setting the appearance seems like lot to me. Also, what user knows what material3 is? It seems to make more sense to place all settings within a common dialog ... but find better names. But first I would have to figure out, how to override the standard background color :-). Switching off material3 appears to be easier, but then we would need to find an appropriate name for it.

**Comment by thetwom** [comment]
good to hear, that I got if finally right :-). 

I still did not find any good infos whether android allows to have user defined colors (like black background or the accent color). Mostly I read that theme colors are always hardcoded. I know that there are apps which support this, but I wonder if I missed something or if these apps use dirty hacks to achieve it. I would not like to use dirty hacks since it  would mean a lot of extra code and quickly becomes error-prone.  Maybe you can point me to some apps, which support this and which are open source, then I could at least check how they do it ...

for direct contact, I do not really like to share data here ... but you could use the gmail-adress from the google-play store entry of the app ...

**Comment by thetwom** [comment]
Closing this now, since this is resolved.
