### ISSUE TITLE
Feature request: option for pure black background for OLED screens

### ISSUE THREAD

**Issue by houlahaj** [thetwom/Tuner#23]
Firstly, thanks for your work on the app! As a dev and a hobby musician, I love this nice open source tuner.

Just wanted to request that you add an option to make the blacks "pure" for OLED screens, as for example fdroid has in its settings.

Perhaps you've already done this in the upcoming release candidate as I see you've reworked the colors but unfortunately, for whatever reason, I was unable to install it on my Android 11 device. Perhaps that deserves a bug report of its own?

**Comment by thetwom** [comment]
Glad you like the app. 

Never came to my mind, that pure black is a benefit but it sounds as it makes sense for OLED. The downside of pure black is that we will loose the shadows. But since the tuner app does not use many shadows anyway this should not really hurt. I guess I should try and see how things look. If things look weird, introducing a user defined setting can be considered, but I would rather avoid it :-). 

Strange that you cannot install the rc on your device. Maybe it's because you have installed the app from fdroid (or the play store). In this case the signing keys do not match (fdroid and google play sign the app with own keys). You could get around this issue by first uninstalling the old app. But in this case you will loose all your settings and user defined instruments ... so only try this, if you can afford loosing your settings. From my side, no need to create an extra report, we can directly discuss things here.

**Comment by houlahaj** [comment]
I had installed it from fdroid; if that uses different signing keys than the apk, that could explain it. I uninstalled it and could install the rc2 fine.

The rc2 with pure black looks really nice! It's not really about power saving, no. It's mostly that it makes the app background blend in with the edges of my phone screen / camera notch. Whenever pure black is available for an app (eg with fdroid, infinity for reddit, newpipe) I turn it on because I find it makes the app more "immersive". But yeah, it's purely an aesthetic choice, I don't care about the extra 30 seconds of battery life it'll bring me haha.

**Comment by houlahaj** [comment]
I see now that it's reverted in rc3.

If at some point you do re-enable it, I definitely suggest adding a user toggle for it, maybe even off by default. Some people don't like pure black, especially if they don't have an OLED display. I see this was also mentioned in the "material you" issue (#20).

**Comment by thetwom** [comment]
well, it is not about reverting at this stage, but at trying around :-). "Material You" makes it a bit harder to change the background color since it will override the color you are actually setting ... I already found a way to circumvent it, but I didn't yet introduce the option to enable it. And before I started doing this,  I was waiting for feedback :-). 

Anyway, good to hear that it looks good. And thanks for the explanation. What I am still wondering about the following:  When reading around I found people saying that the pixels might take some time to "wake up" from pure black meaning not so nice looking animations. Did you experience such effects? Since the the pitch history line is changing all the time, I could imagine we could indeed be affected by such problems ...

**Comment by thetwom** [comment]
And good to hear that the installation problem is solved. Thanks for trying!

**Comment by thetwom** [comment]
Ok, the pure black background is back: [v4.0.0-rc6](https://github.com/thetwom/Tuner/releases/tag/v4.0.0-rc6). You can enable it inside the appearance preference.

**Comment by thetwom** [comment]
this is now official in version [v4.0.0](https://github.com/thetwom/Tuner/releases/tag/v4.0.0). If there are any further issues, please open a new pull request.
