### ISSUE TITLE
Solfage notation

### ISSUE THREAD

**Issue by alirzeya** [thetwom/Tuner#31]
thank you for the great app I had a feature request: I'd enjoy having the option to change the notation to Solfège (Do-Re-Mi-Fa-Sol-La-Si) because that's what many people are familiar with, it'd be cool if there were an option to change the notation.

**Comment by thetwom** [comment]
Thanks for the suggestion. I will try, if this is possible without big layouting issues (the note names become wider...). Might take some time though ...

**Comment by thetwom** [comment]
So here is a first release candidate introducing Solège notation: [v5.3.0-rc1](https://github.com/thetwom/Tuner/releases/tag/v5.3.0-rc1). Feel free to test. Not sure yet, if I should increase the margins to the right, since now the note names are longer. 

I personally have never used this notation. So it would be good to get feedback whether things are correct :-).

**Comment by thetwom** [comment]
Ok, should be fixed now in [v5.3.0-rc2](https://github.com/thetwom/Tuner/releases/tag/v5.3.0-rc2), thanks again for trying and reporting.

**Comment by alirzeya** [comment]
Everything is correct instruments, order, ... 
About the margin and Note names being bigger now, my eyes don't catch any disorientations and app looks perfect for me, I tested everything I could think of and found no issues whatsoever.
Have a great day thanks for your responses. And thank you very much, now I've found my favorite tuner app.

**Comment by thetwom** [comment]
Thanks for the further testing. I will make the modifications official soon. Want to test it a few more days, since I changed some internals, where I want to be sure that nothing unexpected happens (like the issue of crashing at startup :-). 

Although it seems ok so far, I adapted the app a bit more to increase the margins a bit in solfege notation, to avoid that the note names don't touch the side. 

Regarding the instruments selection rectangle, you raise a good question if I should align this with the other plots or not. I will keep this in mind.
