### ISSUE TITLE
Feature request: select key notation/language

### ISSUE THREAD

**Issue by CharHeap** [thetwom/Tuner#37]
Currently the app's key notation (and language) seems to be set according to the system's language (e.g. _values-de_ seems to be used in my case).
It would be nice to have an option to select it manually.

Thank you for this wonderful app!

**Comment by thetwom** [comment]
Yes, the key notation is based on the language. 

Thanks for your interest in the app.

I guess you would prefer the English notation, since it regularly used also in other countries (like Germany) 

So, there are two ways:
- Wait for Android 13, which allows app-specific setting of languages, but then the whole app will be English.
- We could say, the English system is not language-specific, but the "international" notation. And then have the extra option in the settings for "international" notation ... similar to the Do-re-mi-notation. Question is if it is worth, having such an extra setting? Downside is: more settings (I am rather trying to reduce the number of settings, they are too many anyway) and more code. 
 
Would be good to have some opinions here.

**Comment by thetwom** [comment]
Thanks for the feedback. I will give it another thought, but it will take some time, since I am trying to finish other things first.

**Comment by thetwom** [comment]
You can give it a try here: [v5.4.0-rc1](https://github.com/thetwom/Tuner/releases/tag/v5.4.0-rc1) ("international" in the "notation"-settings).

**Comment by thetwom** [comment]
Is now official in [v5.4.0](https://github.com/thetwom/Tuner/releases/tag/v5.4.0).
