### ISSUE TITLE
Add identifying factor to name

### ISSUE THREAD

**Issue by Glitchy-Tozier** [thetwom/Tuner#4]
Hi, you've created a very pretty tuner! It's also nice to find new open-source tuners!  :)

A suggestion: Add something to the name that makes it unique. Searching for "tuner", it's pretty difficult to actually find this app.

**Comment by thetwom** [comment]
Thanks for your feedback. Sorry for the boring name :-). In order to make it easier to find I add the author name ... so you should be able to find it this way? Does this help?

**Comment by Glitchy-Tozier** [comment]
1. You mean "thetwom tuner"? Nope 🙃
2. I meant generally, from a branding perspective, it might be a good idea to have a name that's less generic.

**Comment by thetwom** [comment]
You would have to search for "tuner moessner", I guess :-).

Actually, part of the branding is, that the name is not special. It underlines the fact, that this app does not try to stand out :-). I am offering it just in case people are interested to use it. Of course, I am trying to make it work well (otherwise it would not make sense to got public), and especially to give alternatives to the very limited number of open source tuners. But I am not actively trying to win new users (besides of trying to make it work well :-).

**Comment by Glitchy-Tozier** [comment]
Understood. I agree, making it run well probably is the best thing to do! Should we close this issue?

**Comment by thetwom** [comment]
Yes I think we can close the issue. Nevertheless, thanks for the suggestion!
