### ISSUE TITLE
Screen Content 

### ISSUE THREAD

**Issue by donzefe** [thetwom/Tuner#44]
Hi!
Great Turner, I am much liking the history-graph! Thanks!

For me as Wind Player, it is very much important to see the graph movements as exact as possible. For this reason it would be great to have the graph-section on a bigger surface.

so my suggestion: if selected the chromatic option, do not display the "string section" (the upper part of the screen). Only display the lower part of the screen, the "graph section" on the whole height.

Or a option in the settings to do so would also be good.

Am I understandable?
Best regards!

**Comment by thetwom** [comment]
Hi, thanks for the suggestions. It is perfectly understandable, but it needs a second thought:
- I understand you reasoning, that having this upper part for a chromatic scale seems a bit ambiguous.
- On the other side, the upper part allows to "select" a note such that the target note is locked to this note. Hiding it would take this option away. 

This would leave us with the option that the user manually can hide the upper part. I will give it a though, if this can be done in a good way.

**Comment by donzefe** [comment]
Thanks for your answer! 
That would be great if you could add the option that the user manually can hide the upper part!

Thanks!

**Comment by thetwom** [comment]
Just wanted to give a quick update here. I was thinking quite a bit of a way to nicely introduce such a feature, but up to now I could not come up with a good idea for a nice implementation. In my opinion, such an option should not be hidden in the settings, but it would better need a direct switch next to single sections. But on the other hand this needs space and for landscape mode it would have to work in another way since the layout is different.

So I am a bit puzzled, if we can find a good way to improve the app behaviour for your.

**Comment by donzefe** [comment]
Hi
thanks for the thoughts!

the idea came up in my mind right now: Do this option as another instrument. In the instrument "dropdown" could be listet 2 cromatic options.

if this would be a pleasant and simple option?

**Comment by thetwom** [comment]
This is actually a good idea. What you can do is, to create a custom instrument (just hit the +-Button at the bottom right). For this you can give any name and symbol ... but make sure you have deleted all available strings (just press "delete note" to remove the default string). Then, confirm at the top right and you will have created a custom instrument. 

The result is already close to what you want. But I also created an updated version [v6.1.0-rc2](https://github.com/thetwom/Tuner/releases/tag/v6.1.0-rc2), which you can test. This should then look exactly the way you requested. 

Please let me know, if this works for you. 

(I just realized, that I have to do some fixes in landscape mode, but for testing this should be already fine).

**Comment by donzefe** [comment]
Thanks for the information!

Unfortunately I was not able to install the RC apk on my smartphone. I don't know why... 

I was able to install it on my Laptop on [Anbox](https://github.com/anbox), just to view the visible differences. To be honest: I don't get the differences... :-( 
Anyway: I succeeded by adding an user-configured Instrument with removed all default strings. Like this it's an improvement for me already now!

I believe if you would add such an additional pre-configured instrument, there would be some more people using this app! To get this plain and simple layout its not obvious I think.


Thanks a lot for your work!

**Comment by thetwom** [comment]
I guess, you would have to uninstall the old version first, since the play store/fdroid apps are signed with different keys (but be aware that in this case you will loose all settings and custom instruments). Otherwise you can of course just wait until the changes are official and appear in the app stores ...

Regarding having this as pre-configures instrument, it is of course a good question, whether such a layout is something which is important for a significant amount of people. On the one side having an additional pre-configured instrument does not seem to hurt much, on the other side it can be confusing having two similar "instruments". I think for now, I will keep it as it is. But who knows, maybe this feature will be requested more often in feature ... lets see ...

**Comment by thetwom** [comment]
Closing, this is implemented.

**Comment by donzefe** [comment]
Thank you for your great work!!!
