### ISSUE TITLE
[Feature request] Display how many cents off the note is off from target pitch

### ISSUE THREAD

**Issue by ironfairy42** [thetwom/Tuner#49]
It would make this great app even better if we could have an option to show exactly how flat or sharp the note is in cents and not just the graph (which already works great for most applications). Alternatively, perhaps on scientific mode the graph could also have more markings (every 10 cents or so) so the user can at least better estimate the value in cents.

Thank you :)

**Comment by thetwom** [comment]
Hi, thanks for the interest in the app. Showing the current cent deviations was suggested already, so it might be worth considering. Most difficult question is how to show it :-). Will have to think about it. 

Showing more marks seem a valid alternative, but it might get confusing as soon as users switch to temperaments other than equal temperament, since the markers would not be distributed nicely between notes.

**Comment by thetwom** [comment]
Here is a test version: [v6.3.0-rc1](https://github.com/thetwom/Tuner/releases/tag/v6.3.0-rc1). If you are willing to try, note that you might have to remove your currently installed version first due to different signing keys (unfortunately, this means you will lose your settings and custom instruments ...)

**Comment by ironfairy42** [comment]
Thank you! At least for my use cases this way of displaying the cents already completely solves my problems. If you want to keep experimenting though I can give further feedback on which ways I think are more or less clear, but this is great already.

**Comment by thetwom** [comment]
Thanks for testing. I did a few further improvements (e.g. don't show deviation when it is very far from target) and released it as [v6.3.0](https://github.com/thetwom/Tuner/releases/tag/v6.3.0).
