### ISSUE TITLE
Always have symmetrical screen-padding

### ISSUE THREAD

**Issue by Glitchy-Tozier** [thetwom/Tuner#5]
This is a little weird: (see pink lines)

Device: Samsung Galaxy S9

![Screenshot_20210627-131251_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123542602-c48c1a80-d74a-11eb-9b4f-8da0dc1aa5bc.jpg)

**Comment by thetwom** [comment]
Hm, this is the standard settings dialog of android. I guess, the non-symmetry in due to extra icon space at the left.
But you are right, this does not look right. I will see whether this can be changed!

**Comment by Glitchy-Tozier** [comment]
Is it the back-icon in the app-bar?

**Comment by thetwom** [comment]
actually no, but per default there is space reserved for the icons. But I found an option to switch it off. Will publish a test version soon

**Comment by thetwom** [comment]
hm, the setting I found does not seem to work the same on all screen sizes or systems (not sure, what the reason is). Anyway, I did a little bit more research and the material design guidelines seem to prefer that all titles are aligned with the screen title (see section "Alignment"): [link](https://material.io/design/platform-guidance/android-settings.html#label-and-secondary-text). So it seems to be an issue people could argue about :-)

**Comment by Glitchy-Tozier** [comment]
In that case, I suggest making the right padding bigger I guess.

**Comment by thetwom** [comment]
Increasing the right padding would take up even more of the limited space for the titles.  

On the one side, I agree, that this uneven padding might look weird. On the other side it follows the material guidelines, which is often a good reference, when it comes to design. And since I am no designer, I prefer leaving such decisions to the experts :-). 

The only way I currently see to improve the situation is to add some icons. But I failed often enough to create good-looking icons ... :-)

**Comment by Glitchy-Tozier** [comment]
Are you absolutely sure that this is how the guidelines work? One of the oldest design principles ever is "people like symmetry", so this is really confusing to me! (Also I've never seen unsymmetric settings)
Could it be that that space is only required IF we use icons?

Interestingly, i found an app that incorporates both versions, and both look pretty decent:

![Screenshot_20210628-075008_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/123586816-97d91100-d7e5-11eb-88b3-b5372146b45c.jpg)

![Screenshot_20210628-075019_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/123586827-9b6c9800-d7e5-11eb-87a5-13728ff6f67a.jpg)

**Comment by thetwom** [comment]
It's definitely, what material design proposes. But of course, good design is hard to measure :-). I agree that symmetry is an important design principle. But I guess, it's not always first priority. E.g. when it comes to text alignment. 

As said, I think it's matter of taste. I normally don't like fighting the defaults, since they were made with some reason and it's not often not easy to change them. Often you even have to find several eventualities to make it consistent. 

I will add some icons .. .so it will not look strange anymore to have this left space :-)

**Comment by Glitchy-Tozier** [comment]
Kk, that sould definitely be an imrovement :)

**Comment by Glitchy-Tozier** [comment]
Okay, you improved it a lot! I didn't even know such icons existed.

A few notes I have:

![Screenshot_20210629-133332_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123791549-e10d8b80-d8df-11eb-8dbb-1e517646e0a9.jpg)
![Screenshot_20210629-134048_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123791559-e36fe580-d8df-11eb-99e5-fe341c3468c5.jpg)
Those two settings: I don't know enough about them to judge whether the icons are correct, but if you think they're fine they probably are.

![Screenshot_20210629-134048_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123792019-70b33a00-d8e0-11eb-9cfd-c192f6875cd3.jpg)
I think that adding a unit for what kinds of values we're talking about.  ("5 {unit}")
Are those Windows? Samples? Something else?


![Screenshot_20210629-133308_Tuner.jpg](https://user-images.githubusercontent.com/59611881/123791751-1ade9200-d8e0-11eb-9d0a-c7d92b805cfc.jpg)
Is this a bug? Quite a few icons are missing there.
I can imagine it's difficult to find icons for some of them, but at least the last two should be easy.

Overall, I think adding icons hasn't just improved the design bit also the intuitive understanding of what those settings do.

**Comment by thetwom** [comment]
thanks for the feedback:
- unit of "Anzahl Werte": There is indeed no unit, writing something like "Number of values: 5 values" seems odd :-)
- Icons correct or not: This is of course hard to judge :-). For a first shot, they should be not too bad, I would say.  But I am  sure that they can be improved. I am always amazed what people can describe with very simple icons or emojis ... . 
- Missing icons: I think it is ok to not have icons for everything and I also think this is quite common. But if you have good ideas for icons, please let me know ...

**Comment by Glitchy-Tozier** [comment]
> unit of "Anzahl Werte": There is indeed no unit, writing something like "Number of values: 5 values" seems odd :-)

What are "values" though? Are they single measurements of the 41000 measurements (or whatever amount you use) going on every second?

> I am always amazed what people can describe with very simple icons or emojis.

That's how i felt when I saw your new settings!

> … I also think this is quite common. But if you have good ideas for icons, please let me know ...

Personally I don't think it's a good practice. Also i can't think of a single popular app that has only half of the icons and leaves the remaining settings blank. Can you think of a concrete example?

Regarding the missing icons: I think you know better than I do what exactly all those settings do, so it'll probably be more constructive if you choose the icons.
Regarding the ones I had ideas for:

Reset Settings:  https://fonts.google.com/icons?selected=Material+Icons&icon.query=restart
"Über Tuner": The icon called "info": https://fonts.google.com/icons?selected=Material+Icons&icon.query=info
Obviously you don't have to use those exact icons, but they were the ones I immediately thought of.

**Comment by thetwom** [comment]
yes, you are right, the description is not really good "Anzahl Werte"/"Number of values" really leaves a lot of interpretation. Always hard to come up with something concise :-)

Thanks for the icon suggestions. Will definitely try to add some more. But I don't think that we have to fill all values. Actually I don't think it's bad design practice. Better no icon than a confusing one. As for an example I again refer to my link from above (material design guidelines),  which is probably the most used guideline for android apps. The examples there already include only a few icons.

**Comment by Glitchy-Tozier** [comment]
> Better no icon than a confusing one

I absolutely agree!

**Comment by thetwom** [comment]
I am closing this now, since most requests have been addressed in the meantime and there is now clear issue anymore. Please open new requests if wanted for any specific issues. Thanks for your interest and your support!
