### ISSUE TITLE
Add a simple metronome function.

### ISSUE THREAD

**Issue by GuiSousa135** [thetwom/Tuner#73]
I think it would make the app super complete for every musician, it would be really nice to have a lot of functionality in one tool, instead of two or more different apps.

**Comment by thetwom** [comment]
It is good question, what to prefer: Less apps with more features, or more apps tailored only for specific tasks. While you are asking for the former, at the moment I more go with the latter. There are several reasons for splitting different functionality over different apps:
- User interface is cleaner
- People do not have to install functionality and grant permissions for features they don't want
- It is easier to modernize the underlying code, since you can do it for one app first, and later for the next. You could even drop one app when someone comes up with a superior solution.

Of course, having more features in one app also has advantages like reduced number of apps, and maybe quicker switch between functionality. But for the latter, one needs to integrate the switching between functionality in a nice way to make it really better than just switching apps. 

So at least for now I see more benefits in keeping the apps separate. Especially since a metronome and a tuner have about zero overlap of functionality. So we would not even share a substantial amount of code.

**Comment by Maha-Rajan** [comment]
I agree that creating a single app with more functionality may cause unnecessary complications. Metronome and Tuner as a functionality may not overlap but their usage amongst the musicians do overlap a lot. A simple solution that I could think of is to have a metronome icon in your tuner app and a tuner icon in your metronome app. If the user clicks on the icon they will be promoted to install the respective app if not installed or just open the app if it's already installed. Similar to a link opening it's respective app. This implementation requires minimal implementation by code and UI/UX.

**Comment by thetwom** [comment]
At the moment, I think this is a very specific feature which takes extra space and is not even app-related. Additionally, I would count this as an ad because it advertises another app which is not part of current one. 

I understand, that a quick switch would be useful if people must switch regularly and quickly between the apps, but this seems a very specific request with too many downsides.
