### ISSUE TITLE
Add new instrument icons

### ISSUE THREAD

**Issue by ahangarha** [thetwom/Tuner#81]
Hi

Thanks for the app. This is my primary tool for tuning my instruments.

I wonder if adding new (Persian) instrument icons to the app is possible. I am not an Android developer, but I can see some icons in XML format that I am unfamiliar with. They seem to be very similar to SVG files. Would it work if I shared SVG files with you?

I wanted to see how I can help with making new icons for you (if you would add them to the app)

**Comment by thetwom** [comment]
Thanks for the interest in improving the app. I guess a few more icons could be nice, so I would be glad for ideas. 

I think, it would be important though to follow a few guidelines:
- Try to keep the style similar to the existing ones (we could also think about adapting the existing ones to find a new common style, but for this it would be good to have examples and to agree on a style first)
- Stick to the most important and prominent icons, to make sure that the overall number does not become to high
- Make sure, that the icon are created by you to avoid licensing issues.
- Start with one or two icons and provide them before going on with more, to avoid that you are doing a lot of work and then we cannot agree on some specifics or whatever. I really want to value your work and I don't want to waste your time.

And yes, svg is perfect. See the attached file for an example.
![ic-guitar](https://github.com/thetwom/Tuner/assets/29151788/2e7c0f09-5a83-4960-ad1d-d8b3da4960fd)

**Comment by ahangarha** [comment]
Please check out these icons:

<img alt="tar" src="https://github.com/thetwom/Tuner/assets/11241315/84671cd1-e92d-4ca5-b0b5-4740fc5979b8" width="200" />
<img alt="setar" src="https://github.com/thetwom/Tuner/assets/11241315/0f7e0270-2335-4410-89f7-2f9220ffac27" width="200" />
<img alt="kamancheh" src="https://github.com/thetwom/Tuner/assets/11241315/cc62f34b-c374-43e7-a315-500d00c35aa3" width="200" />

**Comment by thetwom** [comment]
Thanks a lot for the icons. To me they look as the fit good enough to the current style (I don't say that they perfectly fit, since I never had a strong style so there is not perfect fit :-) ). I hope that the degree of detail is not too high, but I guess, this should be better experienced within the app. 

Could you give me the names of these instruments, then I can at get the naming right (its more about file names and descriptions). 

Are you planning to provide more icons? If yes, can you give a rough number?  

For the further way forward, I am proposing the following: 
1. We agree on the rough number of icons
2. You provide the most important ones
3. I integrate it in the app and provide a test version
4. We check if there should be improvements and improve it if necessary
5. Integrating more icons if wanted ...

**Comment by ahangarha** [comment]
I used alt attribute on each image.
From left to right: Tar, Setar, Kamancheh.

I can make more but for my use, these are enough for the time being.

If you need me to make more icons, just let me know. I try to create them in a reasonable time.

**Comment by thetwom** [comment]
Ok, sounds good, will try to include these within the next few days.

**Comment by thetwom** [comment]
Here you can try it: [v6.8.0-rc1](https://github.com/thetwom/Tuner/releases/tag/v6.8.0-rc1). I simplified the icons slightly, but for the small size, this shouldn't be really visible. Android might complain during installation, since this is signed with my own keys (and not fdroid or google). In this case you would have to uninstall the app before. But make sure, you save predefined instrument lists if you want to keep them. And note, that the settings will be lost during removal.

**Comment by ahangarha** [comment]
Thanks for incorporating the new icons in the new release. I just made a typo fix in #83.

**Comment by thetwom** [comment]
Thanks, I created the release [v6.8.0](https://github.com/thetwom/Tuner/releases/tag/v6.8.0) it is now queued to appear on fdroid and google play. Should appear there within the next days.

**Comment by ahangarha** [comment]
Thanks for the smooth process.
Bests
