### ISSUE TITLE
New UI bug. Elements are covering eachother

### ISSUE THREAD

**Issue by anaskaejdar** [thetwom/Tuner#96]
This looks alot like something the UnexpectedKeyboard dev was dealing with the last few days too. I think it was a new version of some kind of UI dependency.

Stuffs are being displayed overlapping in ways they weren't before. For instance, this titlebar thing in the settings is eating the topmost entry, or maybe two entries — I forgot if something else is up there too.

![Screenshot_۲۰۲۴-۱۲-۲۶-۱۶-۲۴-۴۰-۳۰_72e93e00ed3307aff2580573c1323c2c](https://github.com/user-attachments/assets/b7daf56c-0a3f-4f37-9d5e-728e4dc9a5f7)

**Comment by thetwom** [comment]
Thanks for reporting this issue. Seems to be connected to a new behaviour in Android 15 (guess you are on Android 15?). As you say, it is indeed similar to the UnexpectedKeyboard issue, however the solution should hopefully more simple for the tuner app (in theory it should already be able to deal with it, since it uses standard components here, but apparently there is still something wrong ...). Will try to come up with a fix soon.

**Comment by thetwom** [comment]
The issue should now be fixed: [v7.1.0](https://github.com/thetwom/Tuner/releases/tag/v7.1.0). Thanks again for the report.

**Comment by anaskaejdar** [comment]
My pleasure. Thank you! It seems to have worked out beautifully so I'mma close this
